## Lesson 3

In [43]:
import numpy as np
import pandas as pd

## Homework

In [73]:
# 1. Привести различные способы создания объектов типа Series
# Для создания Series можно использовать
# - списки Python или массивы NumPy
# - скалярные значение
# - словари

cities = ['city_1', 'city_2', 'city_3', 'city_4', 'city_5']
population_values = [1001, 1002, 1003, 1004, 1005]
area_values = [9991, 9992, 9993, 9994, 9995]


print('1. Создание объектов типа Series через списки Python')
s_population_list = pd.Series(data=population_values,index=cities, name='Population')
print( s_population_list)
print()

print('2. Создание объектов типа Series через скалярные значения')
s_scalar = pd.Series(data=1000, index=cities, name='Scalar')
print( s_scalar)
print()

print('3. Создание объектов типа Series через словари')
population_dict = {
    'city_1': 1001,
    'city_2': 1002,
    'city_3': 1003,
    'city_4': 1004,
    'city_5': 1005
}
s_population_dict = pd.Series(data=population_dict, name='Population from Dict')
print( s_population_dict)


1. Создание объектов типа Series через списки Python
city_1    1001
city_2    1002
city_3    1003
city_4    1004
city_5    1005
Name: Population, dtype: int64

2. Создание объектов типа Series через скалярные значения
city_1    1000
city_2    1000
city_3    1000
city_4    1000
city_5    1000
Name: Scalar, dtype: int64

3. Создание объектов типа Series через словари
city_1    1001
city_2    1002
city_3    1003
city_4    1004
city_5    1005
Name: Population from Dict, dtype: int64


In [74]:
# 2. Привести различные способы создания объектов типа DataFrame
# DataFrame. Способы создания
# - через объекты Series
# - списки словарей
# - словари объектов Series
# - двумерный массив NumPy
# - структурированный массив Numpy

print('1. Cоздание объектов типа DataFrame через объекты Series ')
population_dict  ={
    'city_1': 1001,
    'city_2': 1002,
    'city_3': 1003,
    'city_4': 1004,
    'city_5': 1005
}
area_dict  ={
    'city_1': 9991,
    'city_2': 9992,
    'city_3': 9993,
    'city_4': 9994,
    'city_5': 9995
}
population = pd.Series(population_dict)
area = pd.Series(area_dict)
states = pd.DataFrame({
    'poputation1':population,
    'area1': area
})
print(states)
print()

print('2. Cоздание объектов типа DataFrame через списки словарей ')
data = [
    {'city': 'city_1', 'population': 1001, 'area': 9991},
    {'city': 'city_2', 'population': 1002, 'area': 9992},
    {'city': 'city_3', 'population': 1003, 'area': 9993},
    {'city': 'city_4', 'population': 1004, 'area': 9994},
    {'city': 'city_5', 'population': 1005, 'area': 9995}
]

df = pd.DataFrame(data).set_index('city')
print(df)
print()

print('3. Cоздание объектов типа DataFrame через словари объектов Series ')
data = {
    'population': [1001, 1002, 1003, 1004, 1005],
    'area': [9991, 9992, 9993, 9994, 9995]
}

df = pd.DataFrame(data, index=['city_1', 'city_2', 'city_3', 'city_4', 'city_5'])
print(df)
print()

print('4. Cоздание объектов типа DataFrame через двумерный массив NumPy ')
arr = np.array([
    [1001, 9991],
    [1002, 9992],
    [1003, 9993],
    [1004, 9994],
    [1005, 9995]
])

df = pd.DataFrame(arr, columns=['population', 'area'], index=[f'city_{i+1}' for i in range(5)])
print(df)
print()

print('5. Cоздание объектов типа DataFrame через структурированный массив Numpy ')
dtype = [('population', int), ('area', int)]
arr = np.array([(1001, 9991), (1002, 9992), (1003, 9993), (1004, 9994), (1005, 9995)],dtype=dtype)

df = pd.DataFrame(arr, index=[f'city_{i+1}' for i in range(5)])
print(df)
print()


1. Cоздание объектов типа DataFrame через объекты Series 
        poputation1  area1
city_1         1001   9991
city_2         1002   9992
city_3         1003   9993
city_4         1004   9994
city_5         1005   9995

2. Cоздание объектов типа DataFrame через списки словарей 
        population  area
city                    
city_1        1001  9991
city_2        1002  9992
city_3        1003  9993
city_4        1004  9994
city_5        1005  9995

3. Cоздание объектов типа DataFrame через словари объектов Series 
        population  area
city_1        1001  9991
city_2        1002  9992
city_3        1003  9993
city_4        1004  9994
city_5        1005  9995

4. Cоздание объектов типа DataFrame через двумерный массив NumPy 
        population  area
city_1        1001  9991
city_2        1002  9992
city_3        1003  9993
city_4        1004  9994
city_5        1005  9995

5. Cоздание объектов типа DataFrame через структурированный массив Numpy 
        population  area
city_1    

In [75]:
# 3. Объедините два объекта Series с неодинаковыми множествами ключей (индексов) так, чтобы вместо NaN было установлено значение 1

pop = pd.Series({
    'city_1': 1001,
    'city_2': 1002,
    'city_3': 1003,
    'city_41': 1004,
    'city_51': 1005
})

area = pd.Series({
    'city_1': 9991,
    'city_2': 9992,
    'city_3': 9993,
    'city_42': 9994,
    'city_52': 9995
})

data = pd.DataFrame({'area1': area, 'pop1': pop}).fillna(1)
print(data)

          area1    pop1
city_1   9991.0  1001.0
city_2   9992.0  1002.0
city_3   9993.0  1003.0
city_41     1.0  1004.0
city_42  9994.0     1.0
city_51     1.0  1005.0
city_52  9995.0     1.0


In [76]:
# 4. Переписать пример с транслирование для DataFrame так, чтобы вычитание происходило по СТОЛБЦАМ

A = rng.integers(0, 10, (3,4))
df = pd.DataFrame(A, columns=['a', 'b', 'c', 'd'])

print("DataFrame:")
print(df)

print("Первый столбец:")
print(df.iloc[:, 0])

print("Вычитание по столбцам:")
print(df.sub(df.iloc[:, 0], axis=0))

DataFrame:
   a  b  c  d
0  0  6  7  1
1  5  3  5  0
2  6  2  5  4
Первый столбец:
0    0
1    5
2    6
Name: a, dtype: int64
Вычитание по столбцам:
   a  b  c  d
0  0  6  7  1
1  0 -2  0 -5
2  0 -4 -1 -2


In [77]:
# 5. На примере объектов DataFrame продемонстрируйте использование методов ffill() и bfill()

data = {
    'A': [1, np.nan, 3, np.nan, 5],
    'B': [np.nan, 7, np.nan, 9, np.nan],
    'C': [10, 20, np.nan, np.nan, 50]
}

df = pd.DataFrame(data)
print("Исходный DataFrame:")
print(df)

# ffill() заполняет пропуски ПОСЛЕДНИМ известным значением сверху вниз:
df1 = df.ffill()
print("После ffill():")
print(df1)

# bfill() заполняет пропуски СЛЕДУЮЩИМ известным значением снизу вверх:
df2 = df.bfill()
print("После bfill():")
print(df2)


Исходный DataFrame:
     A    B     C
0  1.0  NaN  10.0
1  NaN  7.0  20.0
2  3.0  NaN   NaN
3  NaN  9.0   NaN
4  5.0  NaN  50.0
После ffill():
     A    B     C
0  1.0  NaN  10.0
1  1.0  7.0  20.0
2  3.0  7.0  20.0
3  3.0  9.0  20.0
4  5.0  9.0  50.0
После bfill():
     A    B     C
0  1.0  7.0  10.0
1  3.0  7.0  20.0
2  3.0  9.0  50.0
3  5.0  9.0  50.0
4  5.0  NaN  50.0


In [4]:
# Pandas - расширение NumPy(структурированные массивы). Строки и столбцы индексируются метками, а не только числовыми значениями
# Series, DataFrame, Index

In [5]:
#Series
data = pd.Series([0.25,0.5,0.75,1])
print(data)
print(type(data))

print(data.values)
print(data.index)

print(type(data.values))
print(type(data.index))

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
<class 'pandas.core.series.Series'>
[0.25 0.5  0.75 1.  ]
RangeIndex(start=0, stop=4, step=1)
<class 'numpy.ndarray'>
<class 'pandas.core.indexes.range.RangeIndex'>


In [6]:
data = pd.Series([0.25,0.5,0.75,1])
print(data[0])
print(data[1:3])

0.25
1    0.50
2    0.75
dtype: float64


In [7]:
data = pd.Series([0.25,0.5,0.75,1], index = ['a','b','c', 'd'])
print(data)
print(data['a'])
print(data['b':'d'])

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
0.25
b    0.50
c    0.75
d    1.00
dtype: float64


In [8]:
print(type(data.index))

<class 'pandas.core.indexes.base.Index'>


In [9]:
data = pd.Series([0.25,0.5,0.75,1], index = [1,10,7, 'd'])
print(data)
print(data[1])
print(data[10:'d'])

1     0.25
10    0.50
7     0.75
d     1.00
dtype: float64
0.25
10    0.50
7     0.75
d     1.00
dtype: float64


In [10]:
population_dict  ={
    'city_1': 1001,
    'city_2': 1002,
    'city_3': 1003,
    'city_4': 1004,
    'city_5': 1005
}
poputation = pd.Series(population_dict)
print(poputation)
print(poputation['city_4'])
print(poputation['city_4':'city_5'])

city_1    1001
city_2    1002
city_3    1003
city_4    1004
city_5    1005
dtype: int64
1004
city_4    1004
city_5    1005
dtype: int64


In [42]:
# 1. Привести различные способы создания объектов типа Series
# Для создания Series можно использовать
# - списки Python или массивы NumPy
# - скалярные значение
# - словари

cities = ['city_1', 'city_2', 'city_3', 'city_4', 'city_5']
population_values = [1001, 1002, 1003, 1004, 1005]
area_values = [9991, 9992, 9993, 9994, 9995]


print('1. Создание объектов типа Series через списки Python')
s_population_list = pd.Series(data=population_values,index=cities, name='Population')
print( s_population_list)
print()

print('2. Создание объектов типа Series через скалярные значения')
s_scalar = pd.Series(data=1000, index=cities, name='Scalar')
print( s_scalar)
print()

print('2. Создание объектов типа Series через словари')
population_dict = {
    'city_1': 1001,
    'city_2': 1002,
    'city_3': 1003,
    'city_4': 1004,
    'city_5': 1005
}
s_population_dict = pd.Series(data=population_dict, name='Population from Dict')
print( s_population_dict)


1. Создание объектов типа Series через списки Python
city_1    1001
city_2    1002
city_3    1003
city_4    1004
city_5    1005
Name: Population, dtype: int64

2. Создание объектов типа Series через скалярные значения
city_1    1000
city_2    1000
city_3    1000
city_4    1000
city_5    1000
Name: Scalar, dtype: int64

2. Создание объектов типа Series через словари
city_1    1001
city_2    1002
city_3    1003
city_4    1004
city_5    1005
Name: Population from Dict, dtype: int64


In [12]:
## DataFrame - двумерный массив с явно опрделенными индексами. Последовательность согласованных объектов Series.
population_dict  ={
    'city_1': 1001,
    'city_2': 1002,
    'city_3': 1003,
    'city_4': 1004,
    'city_5': 1005
}

area_dict  ={
    'city_1': 9991,
    'city_2': 9992,
    'city_3': 9993,
    'city_4': 9994,
    'city_5': 9995
}
population = pd.Series(population_dict)
area = pd.Series(area_dict)
print(poputation)
print(area)

city_1    1001
city_2    1002
city_3    1003
city_4    1004
city_5    1005
dtype: int64
city_1    9991
city_2    9992
city_3    9993
city_4    9994
city_5    9995
dtype: int64


In [13]:
states = pd.DataFrame({
    'poputation1':population,
    'area1': area
})
print(states)
print(states.values)
print(states.index)
print(states.columns)
print(type(states.values))
print(type(states.index))
print(type(states.columns))

        poputation1  area1
city_1         1001   9991
city_2         1002   9992
city_3         1003   9993
city_4         1004   9994
city_5         1005   9995
[[1001 9991]
 [1002 9992]
 [1003 9993]
 [1004 9994]
 [1005 9995]]
Index(['city_1', 'city_2', 'city_3', 'city_4', 'city_5'], dtype='object')
Index(['poputation1', 'area1'], dtype='object')
<class 'numpy.ndarray'>
<class 'pandas.core.indexes.base.Index'>
<class 'pandas.core.indexes.base.Index'>


In [14]:
print(states['area1'])

city_1    9991
city_2    9992
city_3    9993
city_4    9994
city_5    9995
Name: area1, dtype: int64


In [40]:
# 2. Привести различные способы создания объектов типа DataFrame
# DataFrame. Способы создания
# - через объекты Series
# - списки словарей
# - словари объектов Series
# - двумерный массив NumPy
# - структурированный массив Numpy

print('1. Cоздание объектов типа DataFrame через объекты Series ')
population_dict  ={
    'city_1': 1001,
    'city_2': 1002,
    'city_3': 1003,
    'city_4': 1004,
    'city_5': 1005
}
area_dict  ={
    'city_1': 9991,
    'city_2': 9992,
    'city_3': 9993,
    'city_4': 9994,
    'city_5': 9995
}
population = pd.Series(population_dict)
area = pd.Series(area_dict)
states = pd.DataFrame({
    'poputation1':population,
    'area1': area
})
print(states)
print()

print('2. Cоздание объектов типа DataFrame через списки словарей ')
data = [
    {'city': 'city_1', 'population': 1001, 'area': 9991},
    {'city': 'city_2', 'population': 1002, 'area': 9992},
    {'city': 'city_3', 'population': 1003, 'area': 9993},
    {'city': 'city_4', 'population': 1004, 'area': 9994},
    {'city': 'city_5', 'population': 1005, 'area': 9995}
]

df = pd.DataFrame(data).set_index('city')
print(df)
print()

print('3. Cоздание объектов типа DataFrame через словари объектов Series ')
data = {
    'population': [1001, 1002, 1003, 1004, 1005],
    'area': [9991, 9992, 9993, 9994, 9995]
}

df = pd.DataFrame(data, index=['city_1', 'city_2', 'city_3', 'city_4', 'city_5'])
print(df)
print()

print('4. Cоздание объектов типа DataFrame через двумерный массив NumPy ')
arr = np.array([
    [1001, 9991],
    [1002, 9992],
    [1003, 9993],
    [1004, 9994],
    [1005, 9995]
])

df = pd.DataFrame(arr, columns=['population', 'area'], index=[f'city_{i+1}' for i in range(5)])
print(df)
print()

print('5. Cоздание объектов типа DataFrame через структурированный массив Numpy ')
dtype = [('population', int), ('area', int)]
arr = np.array([(1001, 9991), (1002, 9992), (1003, 9993), (1004, 9994), (1005, 9995)],dtype=dtype)

df = pd.DataFrame(arr, index=[f'city_{i+1}' for i in range(5)])
print(df)
print()


1. Cоздание объектов типа DataFrame через объекты Series 
        poputation1  area1
city_1         1001   9991
city_2         1002   9992
city_3         1003   9993
city_4         1004   9994
city_5         1005   9995

2. Cоздание объектов типа DataFrame через списки словарей 
        population  area
city                    
city_1        1001  9991
city_2        1002  9992
city_3        1003  9993
city_4        1004  9994
city_5        1005  9995

3. Cоздание объектов типа DataFrame через словари объектов Series 
        population  area
city_1        1001  9991
city_2        1002  9992
city_3        1003  9993
city_4        1004  9994
city_5        1005  9995

4. Cоздание объектов типа DataFrame через двумерный массив NumPy 
        population  area
city_1        1001  9991
city_2        1002  9992
city_3        1003  9993
city_4        1004  9994
city_5        1005  9995

5. Cоздание объектов типа DataFrame через структурированный массив Numpy 
        population  area
city_1    

In [16]:
#Index - способ организации ссылки на данные объектов Series и DataFrame. Index - неизменяем, упорядочен, явялется мультимножеством(повторяющиеся значения)
ind = pd.Index([2,3,5,7])
print(ind[1])
print(ind[::2])
# Index следует соглашениям объекта set()

indA = pd.Index([1,2,3,4,5])
indB = pd.Index([1,2,3,4,5,6])
print(indA.intersection(indB))


3
Index([2, 5], dtype='int64')
Index([1, 2, 3, 4, 5], dtype='int64')


In [17]:
# выбрка данных из Series
data = pd.Series([0.25,0.5,0.75,1], index = ['a','b','c', 'd'])
print('a' in data)
print('z' in data)
print(data.keys())

print(list(data.items()))

True
False
Index(['a', 'b', 'c', 'd'], dtype='object')
[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]


In [18]:
data['a'] = 100
data ['z'] = 1000
print(data)
## как одномерный массив


a     100.00
b       0.50
c       0.75
d       1.00
z    1000.00
dtype: float64


In [19]:
data = pd.Series([0.25,0.5,0.75,1], index = ['a','b','c', 'd'])
print(data['a':'c'])
print(data[0:2])
print(data[(data > 0.5) & (data < 1)])
print(data[['a', 'd']])

a    0.25
b    0.50
c    0.75
dtype: float64
a    0.25
b    0.50
dtype: float64
c    0.75
dtype: float64
a    0.25
d    1.00
dtype: float64


In [20]:
data = pd.Series([0.25,0.5,0.75,1], index = [1, 3, 10, 15])
print(data[1])
print(data.loc[1])
print(data.iloc[1])

0.25
0.25
0.5


In [21]:
# выбрка данных из DataFrame
population_dict  ={
    'city_1': 1001,
    'city_2': 1002,
    'city_3': 1003,
    'city_4': 1004,
    'city_5': 1005
}

area_dict  ={
    'city_1': 9991,
    'city_2': 9992,
    'city_3': 9993,
    'city_4': 9994,
    'city_5': 9995
}

pop = pd.Series({
    'city_1': 1001,
    'city_2': 1002,
    'city_3': 1003,
    'city_4': 1004,
    'city_5': 1005
})
area = pd.Series({
    'city_1': 9991,
    'city_2': 9992,
    'city_3': 9993,
    'city_4': 9994,
    'city_5': 9995
})
data = pd.DataFrame({'area1':area,'pop1':pop, 'pop': pop })
print(data)
print(data['area1'])
print(data.area1)

        area1  pop1   pop
city_1   9991  1001  1001
city_2   9992  1002  1002
city_3   9993  1003  1003
city_4   9994  1004  1004
city_5   9995  1005  1005
city_1    9991
city_2    9992
city_3    9993
city_4    9994
city_5    9995
Name: area1, dtype: int64
city_1    9991
city_2    9992
city_3    9993
city_4    9994
city_5    9995
Name: area1, dtype: int64


In [22]:
print(data.pop1 is data['pop1'])
print(data.pop is data['pop'])

True
False


In [23]:
data['new'] = data['area1']
data['new1'] = data['area1'] / data['pop1']
print(data)

# двумерный NumPy массив

        area1  pop1   pop   new      new1
city_1   9991  1001  1001  9991  9.981019
city_2   9992  1002  1002  9992  9.972056
city_3   9993  1003  1003  9993  9.963111
city_4   9994  1004  1004  9994  9.954183
city_5   9995  1005  1005  9995  9.945274


In [24]:
pop = pd.Series({
    'city_1': 1001,
    'city_2': 1002,
    'city_3': 1003,
    'city_4': 1004,
    'city_5': 1005
})
area = pd.Series({
    'city_1': 9991,
    'city_2': 9992,
    'city_3': 9993,
    'city_4': 9994,
    'city_5': 9995
})
data = pd.DataFrame({'area1':area,'pop1':pop })
print(data)
print(data.values)
print(data.T)
print(data['area1'])
print(data.values[0])

        area1  pop1
city_1   9991  1001
city_2   9992  1002
city_3   9993  1003
city_4   9994  1004
city_5   9995  1005
[[9991 1001]
 [9992 1002]
 [9993 1003]
 [9994 1004]
 [9995 1005]]
       city_1  city_2  city_3  city_4  city_5
area1    9991    9992    9993    9994    9995
pop1     1001    1002    1003    1004    1005
city_1    9991
city_2    9992
city_3    9993
city_4    9994
city_5    9995
Name: area1, dtype: int64
[9991 1001]


In [25]:
# атрибуты - индексаторы
data = pd.DataFrame({'area1':area,'pop1':pop, 'pop': pop })
print(data)
print(data.iloc[:3, 1:2])
print(data.loc[:'city_4', 'pop1':'pop'])
print(data.loc[data['pop'] > 1002, ['area1', 'pop']])
data.iloc[0,2] = 99999
print(data)

        area1  pop1   pop
city_1   9991  1001  1001
city_2   9992  1002  1002
city_3   9993  1003  1003
city_4   9994  1004  1004
city_5   9995  1005  1005
        pop1
city_1  1001
city_2  1002
city_3  1003
        pop1   pop
city_1  1001  1001
city_2  1002  1002
city_3  1003  1003
city_4  1004  1004
        area1   pop
city_3   9993  1003
city_4   9994  1004
city_5   9995  1005
        area1  pop1    pop
city_1   9991  1001  99999
city_2   9992  1002   1002
city_3   9993  1003   1003
city_4   9994  1004   1004
city_5   9995  1005   1005


In [26]:
rng = np.random.default_rng()
s = pd.Series(rng.integers(0,10,4))
print(s)
print(np.exp(s))

0    3
1    9
2    4
3    5
dtype: int64
0      20.085537
1    8103.083928
2      54.598150
3     148.413159
dtype: float64


In [27]:
pop = pd.Series({
    'city_1': 1001,
    'city_2': 1002,
    'city_3': 1003,
    'city_41': 1004,
    'city_51': 1005
})
area = pd.Series({
    'city_1': 9991,
    'city_2': 9992,
    'city_3': 9993,
    'city_42': 9994,
    'city_52': 9995
})
data = pd.DataFrame({'area1':area,'pop1':pop })
print(data)

          area1    pop1
city_1   9991.0  1001.0
city_2   9992.0  1002.0
city_3   9993.0  1003.0
city_41     NaN  1004.0
city_42  9994.0     NaN
city_51     NaN  1005.0
city_52  9995.0     NaN


In [44]:
# 3. Объедините два объекта Series с неодинаковыми множествами ключей (индексов) так, чтобы вместо NaN было установлено значение 1

pop = pd.Series({
    'city_1': 1001,
    'city_2': 1002,
    'city_3': 1003,
    'city_41': 1004,
    'city_51': 1005
})

area = pd.Series({
    'city_1': 9991,
    'city_2': 9992,
    'city_3': 9993,
    'city_42': 9994,
    'city_52': 9995
})

data = pd.DataFrame({'area1': area, 'pop1': pop}).fillna(1)
print(data)

          area1    pop1
city_1   9991.0  1001.0
city_2   9992.0  1002.0
city_3   9993.0  1003.0
city_41     1.0  1004.0
city_42  9994.0     1.0
city_51     1.0  1005.0
city_52  9995.0     1.0


In [29]:
dfA = pd.DataFrame(rng.integers(0,10,(2,2)), columns=['a','b'])
dfB = pd.DataFrame(rng.integers(0,10,(3,3)), columns=['a','b', 'c'])

print(dfA)
print(dfB)
print(dfA + dfB)

   a  b
0  3  6
1  7  6
   a  b  c
0  6  8  6
1  1  6  1
2  8  7  2
     a     b   c
0  9.0  14.0 NaN
1  8.0  12.0 NaN
2  NaN   NaN NaN


In [30]:
rng = np.random.default_rng(1)
A = rng.integers(0, 10, (3,4))
print(A[0])
print(A - A[0])

[4 5 7 9]
[[ 0  0  0  0]
 [-4 -4  1  0]
 [-2 -2  1 -5]]


In [46]:
df = pd.DataFrame(A, columns=['a', 'b', 'c', 'd'])
print(df)
print(df.iloc[0])
print(df - df.iloc[0])
print(df.iloc[0, ::2])
print(df - df.iloc[0, ::2])

   a  b  c  d
0  2  8  2  4
1  6  5  0  0
2  8  7  8  5
a    2
b    8
c    2
d    4
Name: 0, dtype: int64
   a  b  c  d
0  0  0  0  0
1  4 -3 -2 -4
2  6 -1  6  1
a    2
c    2
Name: 0, dtype: int64
     a   b    c   d
0  0.0 NaN  0.0 NaN
1  4.0 NaN -2.0 NaN
2  6.0 NaN  6.0 NaN


In [59]:
# 4. Переписать пример с транслирование для DataFrame так, чтобы вычитание происходило по СТОЛБЦАМ

A = rng.integers(0, 10, (3,4))
df = pd.DataFrame(A, columns=['a', 'b', 'c', 'd'])

print("DataFrame:")
print(df)

print("Первый столбец:")
print(df.iloc[:, 0])

print("Вычитание по столбцам:")
print(df.sub(df.iloc[:, 0], axis=0))

DataFrame:
   a  b  c  d
0  8  8  3  0
1  7  8  4  1
2  1  3  7  3
Первый столбец:
0    8
1    7
2    1
Name: a, dtype: int64
Вычитание по столбцам:
   a  b  c  d
0  0  0 -5 -8
1  0  1 -3 -6
2  0  2  6  2


In [33]:
# NA  -значения: NaN, null


# Pandas. два способа хранения отсут. значений
# индикаторы NaN, None
# null

# None - объект(накладные расходы). Не работает с sum, min
val = np.array([1,2,3])
print(val.sum())

6


In [34]:
val = np.array([1,2,3, None])
print(val.sum())

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [60]:
val1 = np.array([1,2,3, np.nan])
print(val1)
print(val1.sum())
print(np.nansum(val1))

[ 1.  2.  3. nan]
nan
6.0


In [61]:
x = pd.Series(range(10), dtype = int)
print(x)

x[0] = None
x[1]  =np.nan
print(x)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64
0    NaN
1    NaN
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64


In [62]:
x1 = pd.Series(['a', 'b', 'c'])
print(x1)

x1[0] = None
x1[1]  =np.nan
print(x1)

0    a
1    b
2    c
dtype: object
0    None
1     NaN
2       c
dtype: object


In [63]:
x2 = pd.Series([1,2,3, np.nan, None, pd.NA])
print(x2)

0       1
1       2
2       3
3     NaN
4    None
5    <NA>
dtype: object


In [64]:
x3 = pd.Series([1,2,3, np.nan, None, pd.NA], dtype = 'Int32')
print(x3)

0       1
1       2
2       3
3    <NA>
4    <NA>
5    <NA>
dtype: Int32


In [65]:
print(x3.isnull())
print(x3[x3.isnull()])
print(x3[x3.notnull()])

0    False
1    False
2    False
3     True
4     True
5     True
dtype: bool
3    <NA>
4    <NA>
5    <NA>
dtype: Int32
0    1
1    2
2    3
dtype: Int32


In [66]:
print(x3.dropna())

0    1
1    2
2    3
dtype: Int32


In [67]:
df =pd.DataFrame([
    [1,2,3, np.nan, None, pd.NA],
    [1,2,3,4,5,6],
    [1, np.nan,3,4,np.nan,6]
])
print(df)
print(df.dropna())
print()
print(df.dropna(axis = 0))
print(df.dropna(axis = 1))

   0    1  2    3    4     5
0  1  2.0  3  NaN  NaN  <NA>
1  1  2.0  3  4.0  5.0     6
2  1  NaN  3  4.0  NaN     6
   0    1  2    3    4  5
1  1  2.0  3  4.0  5.0  6

   0    1  2    3    4  5
1  1  2.0  3  4.0  5.0  6
   0  2
0  1  3
1  1  3
2  1  3


In [68]:
# how
# all - все значания NA
# any  - хотя бы одно значение
# thresh = x, остается если присутствует миннимум x непустых значений
df =pd.DataFrame([
    [1,2,3, np.nan, None, pd.NA],
    [1,2,3,None,5,6],
    [1, np.nan,3,None,np.nan,6]
])
print(df)
print(df.dropna(axis = 1, how = 'all'))
print(df.dropna(axis = 1, how = 'any'))
print(df.dropna(axis = 1, thresh = 2))

   0    1  2   3    4     5
0  1  2.0  3 NaN  NaN  <NA>
1  1  2.0  3 NaN  5.0     6
2  1  NaN  3 NaN  NaN     6
   0    1  2    4     5
0  1  2.0  3  NaN  <NA>
1  1  2.0  3  5.0     6
2  1  NaN  3  NaN     6
   0  2
0  1  3
1  1  3
2  1  3
   0    1  2     5
0  1  2.0  3  <NA>
1  1  2.0  3     6
2  1  NaN  3     6


In [71]:
# 5. На примере объектов DataFrame продемонстрируйте использование методов ffill() и bfill()

data = {
    'A': [1, np.nan, 3, np.nan, 5],
    'B': [np.nan, 7, np.nan, 9, np.nan],
    'C': [10, 20, np.nan, np.nan, 50]
}

df = pd.DataFrame(data)
print("Исходный DataFrame:")
print(df)

# ffill() заполняет пропуски ПОСЛЕДНИМ известным значением сверху вниз:
df1 = df.ffill()
print("После ffill():")
print(df1)

# bfill() заполняет пропуски СЛЕДУЮЩИМ известным значением снизу вверх:
df2 = df.bfill()
print("После bfill():")
print(df2)


Исходный DataFrame:
     A    B     C
0  1.0  NaN  10.0
1  NaN  7.0  20.0
2  3.0  NaN   NaN
3  NaN  9.0   NaN
4  5.0  NaN  50.0
После ffill():
     A    B     C
0  1.0  NaN  10.0
1  1.0  7.0  20.0
2  3.0  7.0  20.0
3  3.0  9.0  20.0
4  5.0  9.0  50.0
После bfill():
     A    B     C
0  1.0  7.0  10.0
1  3.0  7.0  20.0
2  3.0  9.0  50.0
3  5.0  9.0  50.0
4  5.0  NaN  50.0
