## Lesson 4

In [4]:
import numpy as np
import pandas as pd

## Homework

In [64]:
# # 1. Разобраться как использовать мультииндексные ключи в данном примере
index = [
    ('city_1', 2010),

    ('city_1', 2020),

    ('city_2', 2010),

    ('city_2', 2010),

    ('city_3', 2010),

    ('city_3', 2020),
    ]

population  = [
    101,
    201,
    101,
    201,
    101,
    201,
]
pop = pd.Series(population, index = index)
print(pop)

index = pd.MultiIndex.from_tuples(index)
pop = pop.reindex(index)
print(pop)


pop_df = pd.DataFrame(
    {
    'total': pop,
    'something':[
        10,
        11,
        12,
        13,
        14,
        15,
    ]
}
)
print(pop_df)
print()
print(pop_df['something'])
print()
pop_df_1 = pop_df.loc['city_1', 'something']

pop_df_2 = pop_df.loc[['city_1', 'city_3'], 'something']

pop_df_3 = pop_df.loc[['city_1', 'city_3'], ['something', 'total']]

print(pop_df_1)
print()
print(pop_df_2)
print()
print(pop_df_3)

(city_1, 2010)    101
(city_1, 2020)    201
(city_2, 2010)    101
(city_2, 2010)    201
(city_3, 2010)    101
(city_3, 2020)    201
dtype: int64
city_1  2010    101
        2020    201
city_2  2010    101
        2010    201
city_3  2010    101
        2020    201
dtype: int64
             total  something
city_1 2010    101         10
       2020    201         11
city_2 2010    101         12
       2010    201         13
city_3 2010    101         14
       2020    201         15

city_1  2010    10
        2020    11
city_2  2010    12
        2010    13
city_3  2010    14
        2020    15
Name: something, dtype: int64

2010    10
2020    11
Name: something, dtype: int64

city_1  2010    10
        2020    11
city_3  2010    14
        2020    15
Name: something, dtype: int64

             something  total
city_1 2010         10    101
       2020         11    201
city_3 2010         14    101
       2020         15    201


In [65]:
# 2. Из получившихся данных выбрать данные по
# - 2020 году (для всех столбцов)
# - job_1 (для всех строк)
# - для city_1 и job_2


index = pd.MultiIndex.from_product(
    [
        ['city_1', 'city_2'],
        [2010, 2020]
    ],
    names = ['city', 'year']
)
print(index)

columns = pd.MultiIndex.from_product(
    [
        ['person_1', 'person_2', 'person_3'],
        ['job_1', 'job_2']
    ],
    names = ['worker', 'job']
)

rng = np.random.default_rng(1)
data = rng.random((4,6))
print(data)

data_df = pd.DataFrame(data, index = index, columns = columns)
print(data_df)
print()
print('2. Из получившихся данных выбрать данные по ')
print()
print('- 2020 году (для всех столбцов)')
data_df_1 = data_df.loc[(slice(None), 2020), :]
print(data_df_1)
print()
print('- job_1 (для всех строк)')
data_df_2 = data_df.loc[:, (slice(None), 'job_1')]
print(data_df_2)
print()
print('- для city_1 и job_2 ')
data_df_3 = data_df.loc['city_1', (slice(None), 'job_2')]
print(data_df_3)

MultiIndex([('city_1', 2010),
            ('city_1', 2020),
            ('city_2', 2010),
            ('city_2', 2020)],
           names=['city', 'year'])
[[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145 0.42332645]
 [0.82770259 0.40919914 0.54959369 0.02755911 0.75351311 0.53814331]
 [0.32973172 0.7884287  0.30319483 0.45349789 0.1340417  0.40311299]
 [0.20345524 0.26231334 0.75036467 0.28040876 0.48519097 0.9807372 ]]
worker       person_1            person_2            person_3          
job             job_1     job_2     job_1     job_2     job_1     job_2
city   year                                                            
city_1 2010  0.511822  0.950464  0.144160  0.948649  0.311831  0.423326
       2020  0.827703  0.409199  0.549594  0.027559  0.753513  0.538143
city_2 2010  0.329732  0.788429  0.303195  0.453498  0.134042  0.403113
       2020  0.203455  0.262313  0.750365  0.280409  0.485191  0.980737

2. Из получившихся данных выбрать данные по 

- 2020 году (для

In [66]:
# 3. Взять за основу DataFrame со следующей структурой
index = pd.MultiIndex.from_product(
    [
        ['city_1', 'city_2'],
        [2010, 2020]
    ],
    names=['city', 'year']
)
columns = pd.MultiIndex.from_product(
    [
        ['person_1', 'person_2', 'person_3'],
        ['job_1', 'job_2']
    ],
    names=['worker', 'job']
)

# Выполнить запрос на получение следующих данных
# - все данные по person_1 и person_3
# - все данные по первому городу и первым двум person-ам (с использование срезов)


rng = np.random.default_rng(1)
data = rng.random((4,6))
print(data)

data_df = pd.DataFrame(data, index = index, columns = columns)
print(data_df)

print('3. Выполнить запрос на получение следующих данных ')
print()
print('- все данные по person_1 и person_3')
data_df_1 = data_df.loc[:, (['person_1','person_3'], slice(None))]
print(data_df_1)
print()

print('все данные по первому городу и первым двум person-ам (с использование срезов)')
data_df_2 = data_df.loc[('city_1', slice(None)), (['person_1', 'person_2'], slice(None))]
print(data_df_2)
print()


# Приведите пример (самостоятельно) с использованием pd.IndexSlice
idx = pd.IndexSlice

print("Приведите пример (самостоятельно) с использованием pd.IndexSlice\n")

print("- Все данные по person_1 и person_3")
data_df_3 = data_df.loc[:, idx[['person_1', 'person_3'], :]]
print(data_df_3)
print()

print("- Все данные по первому городу и первым двум person-ам")
data_df_4 = data_df.loc[
    idx['city_1', :],
    idx[:'person_2', :]
]
print(data_df_4)


[[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145 0.42332645]
 [0.82770259 0.40919914 0.54959369 0.02755911 0.75351311 0.53814331]
 [0.32973172 0.7884287  0.30319483 0.45349789 0.1340417  0.40311299]
 [0.20345524 0.26231334 0.75036467 0.28040876 0.48519097 0.9807372 ]]
worker       person_1            person_2            person_3          
job             job_1     job_2     job_1     job_2     job_1     job_2
city   year                                                            
city_1 2010  0.511822  0.950464  0.144160  0.948649  0.311831  0.423326
       2020  0.827703  0.409199  0.549594  0.027559  0.753513  0.538143
city_2 2010  0.329732  0.788429  0.303195  0.453498  0.134042  0.403113
       2020  0.203455  0.262313  0.750365  0.280409  0.485191  0.980737
3. Выполнить запрос на получение следующих данных 

- все данные по person_1 и person_3
worker       person_1            person_3          
job             job_1     job_2     job_1     job_2
city   year                

In [67]:
#4. Привести пример использования inner и outer джойнов для Series (данные примера скорее всего нужно изменить)
ser1 = pd.Series(['a', 'b', 'c'], index=[1,2,3])
ser2 = pd.Series(['b', 'c', 'f'], index=[2,3,4])

print("Outer join (объединение всех):")
print(pd.concat([ser1, ser2], axis=1, join='outer'))

print("Inner join (только общие):")
print(pd.concat([ser1, ser2], axis=1, join='inner'))


# print (pd.concat([ser1, ser2], join='outer'))
# print (pd.concat([ser1, ser2], join='inner'))

Outer join (объединение всех):
     0    1
1    a  NaN
2    b    b
3    c    c
4  NaN    f
Inner join (только общие):
   0  1
2  b  b
3  c  c


In [5]:
# Если размерность данных больше 2, то используют иерархическую индексацию(мультииндекс). в один идекс включается несколько уровней.

index = [
    ('city_1', 2010),
    ('city_1', 2020),
    ('city_2', 2010),
    ('city_2', 2020),
    ('city_3', 2010),
    ('city_3', 2020),
    ]

population  = [
    101,
    201,
    101,
    201,
    101,
    201
]
pop = pd.Series(population, index = index)
print(pop)

(city_1, 2010)    101
(city_1, 2020)    201
(city_2, 2010)    101
(city_2, 2020)    201
(city_3, 2010)    101
(city_3, 2020)    201
dtype: int64


In [6]:
# print(pop[[i for i in pop.index if i[1] == 2020]])

index = pd.MultiIndex.from_tuples(index)
pop = pop.reindex(index)
print(pop)
print(pop[:, 2020])

city_1  2010    101
        2020    201
city_2  2010    101
        2020    201
city_3  2010    101
        2020    201
dtype: int64
city_1    201
city_2    201
city_3    201
dtype: int64


In [7]:
pop_df = pop.unstack()
print(pop_df)

print(pop_df.stack())

        2010  2020
city_1   101   201
city_2   101   201
city_3   101   201
city_1  2010    101
        2020    201
city_2  2010    101
        2020    201
city_3  2010    101
        2020    201
dtype: int64


In [8]:
index = [
    ('city_1', 2010,1),
    ('city_1', 2010,2),

    ('city_1', 2020,1),
    ('city_1', 2020,2),

    ('city_2', 2010,1),
    ('city_2', 2010,2),

    ('city_2', 2020,1),
    ('city_2', 2020,2),

    ('city_3', 2010,1),
    ('city_3', 2010,2),

    ('city_3', 2020,1),
    ('city_3', 2020,2),
    ]

population  = [
    101,
    1010,
    201,
    2010,
    101,
    1010,
    201,
    2010,
    101,
    1010,
    201,
    2010
]

pop = pd.Series(population, index = index)
print(pop)


(city_1, 2010, 1)     101
(city_1, 2010, 2)    1010
(city_1, 2020, 1)     201
(city_1, 2020, 2)    2010
(city_2, 2010, 1)     101
(city_2, 2010, 2)    1010
(city_2, 2020, 1)     201
(city_2, 2020, 2)    2010
(city_3, 2010, 1)     101
(city_3, 2010, 2)    1010
(city_3, 2020, 1)     201
(city_3, 2020, 2)    2010
dtype: int64


In [9]:
index = pd.MultiIndex.from_tuples(index)
pop = pop.reindex(index)
print(pop)
print(pop[:, 2010])
print(pop[:,:, 2])

city_1  2010  1     101
              2    1010
        2020  1     201
              2    2010
city_2  2010  1     101
              2    1010
        2020  1     201
              2    2010
city_3  2010  1     101
              2    1010
        2020  1     201
              2    2010
dtype: int64
city_1  1     101
        2    1010
city_2  1     101
        2    1010
city_3  1     101
        2    1010
dtype: int64
city_1  2010    1010
        2020    2010
city_2  2010    1010
        2020    2010
city_3  2010    1010
        2020    2010
dtype: int64


In [10]:
pop_df = pop.unstack()
print(pop_df)

print(pop_df.stack())

               1     2
city_1 2010  101  1010
       2020  201  2010
city_2 2010  101  1010
       2020  201  2010
city_3 2010  101  1010
       2020  201  2010
city_1  2010  1     101
              2    1010
        2020  1     201
              2    2010
city_2  2010  1     101
              2    1010
        2020  1     201
              2    2010
city_3  2010  1     101
              2    1010
        2020  1     201
              2    2010
dtype: int64


In [11]:
index = [
    ('city_1', 2010),

    ('city_1', 2020),

    ('city_2', 2010),

    ('city_2', 2010),

    ('city_3', 2010),

    ('city_3', 2020),
    ]

population  = [
    101,
    201,
    101,
    201,
    101,
    201,
]
pop = pd.Series(population, index = index)
print(pop)

index = pd.MultiIndex.from_tuples(index)
pop = pop.reindex(index)
print(pop)


pop_df = pd.DataFrame(
    {
    'total': pop,
    'something':[
        10,
        11,
        12,
        13,
        14,
        15,
    ]
}
)
print(pop_df)
print(pop_df['something'])

(city_1, 2010)    101
(city_1, 2020)    201
(city_2, 2010)    101
(city_2, 2010)    201
(city_3, 2010)    101
(city_3, 2020)    201
dtype: int64
city_1  2010    101
        2020    201
city_2  2010    101
        2010    201
city_3  2010    101
        2020    201
dtype: int64
             total  something
city_1 2010    101         10
       2020    201         11
city_2 2010    101         12
       2010    201         13
city_3 2010    101         14
       2020    201         15
city_1  2010    10
        2020    11
city_2  2010    12
        2010    13
city_3  2010    14
        2020    15
Name: something, dtype: int64


In [12]:
pop_df_1 = pop_df.loc['city_1', 'something']
pop_df_2 = pop_df.loc[['city_1', 'city_3'], 'something']
pop_df_3 = pop_df.loc[['city_1', 'city_3'], ['something', 'total']]

print(pop_df_1)
print(pop_df_2)
print(pop_df_3)

2010    10
2020    11
Name: something, dtype: int64
city_1  2010    10
        2020    11
city_3  2010    14
        2020    15
Name: something, dtype: int64
             something  total
city_1 2010         10    101
       2020         11    201
city_3 2010         14    101
       2020         15    201


In [33]:
# # 1. Разобраться как использовать мультииндексные ключи в данном примере
index = [
    ('city_1', 2010),

    ('city_1', 2020),

    ('city_2', 2010),

    ('city_2', 2010),

    ('city_3', 2010),

    ('city_3', 2020),
    ]

population  = [
    101,
    201,
    101,
    201,
    101,
    201,
]
pop = pd.Series(population, index = index)
print(pop)

index = pd.MultiIndex.from_tuples(index)
pop = pop.reindex(index)
print(pop)


pop_df = pd.DataFrame(
    {
    'total': pop,
    'something':[
        10,
        11,
        12,
        13,
        14,
        15,
    ]
}
)
print(pop_df)
print()
print(pop_df['something'])
print()
pop_df_1 = pop_df.loc['city_1', 'something']

pop_df_2 = pop_df.loc[['city_1', 'city_3'], 'something']

pop_df_3 = pop_df.loc[['city_1', 'city_3'], ['something', 'total']]

print(pop_df_1)
print()
print(pop_df_2)
print()
print(pop_df_3)

(city_1, 2010)    101
(city_1, 2020)    201
(city_2, 2010)    101
(city_2, 2010)    201
(city_3, 2010)    101
(city_3, 2020)    201
dtype: int64
city_1  2010    101
        2020    201
city_2  2010    101
        2010    201
city_3  2010    101
        2020    201
dtype: int64
             total  something
city_1 2010    101         10
       2020    201         11
city_2 2010    101         12
       2010    201         13
city_3 2010    101         14
       2020    201         15

city_1  2010    10
        2020    11
city_2  2010    12
        2010    13
city_3  2010    14
        2020    15
Name: something, dtype: int64

2010    10
2020    11
Name: something, dtype: int64

city_1  2010    10
        2020    11
city_3  2010    14
        2020    15
Name: something, dtype: int64

             something  total
city_1 2010         10    101
       2020         11    201
city_3 2010         14    101
       2020         15    201


In [14]:
#Создать мультииндексы
## - список массивов, задающих список значений индексов на каждом уровне


i1 = pd.MultiIndex.from_arrays(
    [
        ['a', 'a', 'b', 'b'],
        [1, 2, 1, 2]
    ]
)
print(i1)

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )


In [15]:
#список кортежей
i2 = pd.MultiIndex.from_tuples(
    [
        ('a', 1),
        ('a', 2),
        ('b', 1),
        ('b', 2)
    ]
)
print(i2)

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )


In [16]:
# декартово произведение
i3 = pd.MultiIndex.from_product(
    [
        ['a', 'b'],
        [1,2]
    ]
)
print(i3)

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )


In [17]:
# описание внутреннего представления: levels, codes
i4 = pd.MultiIndex(
    levels = [
        ['a', 'b', 'c'],
        [1,2]
    ],
    codes = [
        [0,0,1,1,2,2],
        [0,1,0,1,0,1]
    ]
)
print(i4)

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )


In [18]:
# Уровням можно задавать названия
data = {
    ('city_1', 2010):100,
    ('city_1', 2020):200,
    ('city_2', 2010):100,
    ('city_2', 2020):200,
}
s = pd.Series(data)
print(s)

s.index.names = ['city', 'year']
print(s)

city_1  2010    100
        2020    200
city_2  2010    100
        2020    200
dtype: int64
city    year
city_1  2010    100
        2020    200
city_2  2010    100
        2020    200
dtype: int64


In [19]:
index = pd.MultiIndex.from_product(
    [
        ['city_1', 'city_2'],
        [2010, 2020]
    ],
    names = ['city', 'year']
)
print(index)

columns = pd.MultiIndex.from_product(
    [
        ['person_1', 'person_2', 'person_3'],
        ['job_1', 'job_2']
    ],
    names = ['worker', 'job']
)

rng = np.random.default_rng(1)
data = rng.random((4,6))
print(data)

data_df = pd.DataFrame(data, index = index, columns = columns)
print(data_df)

MultiIndex([('city_1', 2010),
            ('city_1', 2020),
            ('city_2', 2010),
            ('city_2', 2020)],
           names=['city', 'year'])
[[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145 0.42332645]
 [0.82770259 0.40919914 0.54959369 0.02755911 0.75351311 0.53814331]
 [0.32973172 0.7884287  0.30319483 0.45349789 0.1340417  0.40311299]
 [0.20345524 0.26231334 0.75036467 0.28040876 0.48519097 0.9807372 ]]
worker       person_1            person_2            person_3          
job             job_1     job_2     job_1     job_2     job_1     job_2
city   year                                                            
city_1 2010  0.511822  0.950464  0.144160  0.948649  0.311831  0.423326
       2020  0.827703  0.409199  0.549594  0.027559  0.753513  0.538143
city_2 2010  0.329732  0.788429  0.303195  0.453498  0.134042  0.403113
       2020  0.203455  0.262313  0.750365  0.280409  0.485191  0.980737


In [42]:
# 2. Из получившихся данных выбрать данные по
# - 2020 году (для всех столбцов)
# - job_1 (для всех строк)
# - для city_1 и job_2


index = pd.MultiIndex.from_product(
    [
        ['city_1', 'city_2'],
        [2010, 2020]
    ],
    names = ['city', 'year']
)
print(index)

columns = pd.MultiIndex.from_product(
    [
        ['person_1', 'person_2', 'person_3'],
        ['job_1', 'job_2']
    ],
    names = ['worker', 'job']
)

rng = np.random.default_rng(1)
data = rng.random((4,6))
print(data)

data_df = pd.DataFrame(data, index = index, columns = columns)
print(data_df)
print()
print('2. Из получившихся данных выбрать данные по ')
print()
print('- 2020 году (для всех столбцов)')
data_df_1 = data_df.loc[(slice(None), 2020), :]
print(data_df_1)
print()
print('- job_1 (для всех строк)')
data_df_2 = data_df.loc[:, (slice(None), 'job_1')]
print(data_df_2)
print()
print('- для city_1 и job_2 ')
data_df_3 = data_df.loc['city_1', (slice(None), 'job_2')]
print(data_df_3)

MultiIndex([('city_1', 2010),
            ('city_1', 2020),
            ('city_2', 2010),
            ('city_2', 2020)],
           names=['city', 'year'])
[[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145 0.42332645]
 [0.82770259 0.40919914 0.54959369 0.02755911 0.75351311 0.53814331]
 [0.32973172 0.7884287  0.30319483 0.45349789 0.1340417  0.40311299]
 [0.20345524 0.26231334 0.75036467 0.28040876 0.48519097 0.9807372 ]]
worker       person_1            person_2            person_3          
job             job_1     job_2     job_1     job_2     job_1     job_2
city   year                                                            
city_1 2010  0.511822  0.950464  0.144160  0.948649  0.311831  0.423326
       2020  0.827703  0.409199  0.549594  0.027559  0.753513  0.538143
city_2 2010  0.329732  0.788429  0.303195  0.453498  0.134042  0.403113
       2020  0.203455  0.262313  0.750365  0.280409  0.485191  0.980737

2. Из получившихся данных выбрать данные по 

- 2020 году (для

In [21]:
## индексация и срезы( по мультииндексу)
data = {
    ('city_1', 2010):100,
    ('city_1', 2020):200,
    ('city_2', 2010):1001,
    ('city_2', 2020):2001,
    ('city_3', 2010):10001,
    ('city_3', 2020):20001,
}
s = pd.Series(data)
print(s)
s.index.names = ['city', 'year']
print(s)

print(s['city_1', 2010])

print(s.loc['city_1': 'city_2'])

print(s[:, 2010])

print(s[s>2000])

print(s.loc[['city_1', 'city_3']])

city_1  2010      100
        2020      200
city_2  2010     1001
        2020     2001
city_3  2010    10001
        2020    20001
dtype: int64
city    year
city_1  2010      100
        2020      200
city_2  2010     1001
        2020     2001
city_3  2010    10001
        2020    20001
dtype: int64
100
city    year
city_1  2010     100
        2020     200
city_2  2010    1001
        2020    2001
dtype: int64
city
city_1      100
city_2     1001
city_3    10001
dtype: int64
city    year
city_2  2020     2001
city_3  2010    10001
        2020    20001
dtype: int64
city    year
city_1  2010      100
        2020      200
city_3  2010    10001
        2020    20001
dtype: int64


In [49]:
# 3. Взять за основу DataFrame со следующей структурой
index = pd.MultiIndex.from_product(
    [
        ['city_1', 'city_2'],
        [2010, 2020]
    ],
    names=['city', 'year']
)
columns = pd.MultiIndex.from_product(
    [
        ['person_1', 'person_2', 'person_3'],
        ['job_1', 'job_2']
    ],
    names=['worker', 'job']
)

# Выполнить запрос на получение следующих данных
# - все данные по person_1 и person_3
# - все данные по первому городу и первым двум person-ам (с использование срезов)


rng = np.random.default_rng(1)
data = rng.random((4,6))
print(data)

data_df = pd.DataFrame(data, index = index, columns = columns)
print(data_df)

print('3. Выполнить запрос на получение следующих данных ')
print()
print('- все данные по person_1 и person_3')
data_df_1 = data_df.loc[:, (['person_1','person_3'], slice(None))]
print(data_df_1)
print()

print('все данные по первому городу и первым двум person-ам (с использование срезов)')
data_df_2 = data_df.loc[('city_1', slice(None)), (['person_1', 'person_2'], slice(None))]
print(data_df_2)
print()


# Приведите пример (самостоятельно) с использованием pd.IndexSlice
idx = pd.IndexSlice

print("Приведите пример (самостоятельно) с использованием pd.IndexSlice\n")

print("- Все данные по person_1 и person_3")
data_df_3 = data_df.loc[:, idx[['person_1', 'person_3'], :]]
print(data_df_3)
print()

print("- Все данные по первому городу и первым двум person-ам")
data_df_4 = data_df.loc[
    idx['city_1', :],
    idx[:'person_2', :]
]
print(data_df_4)


[[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145 0.42332645]
 [0.82770259 0.40919914 0.54959369 0.02755911 0.75351311 0.53814331]
 [0.32973172 0.7884287  0.30319483 0.45349789 0.1340417  0.40311299]
 [0.20345524 0.26231334 0.75036467 0.28040876 0.48519097 0.9807372 ]]
worker       person_1            person_2            person_3          
job             job_1     job_2     job_1     job_2     job_1     job_2
city   year                                                            
city_1 2010  0.511822  0.950464  0.144160  0.948649  0.311831  0.423326
       2020  0.827703  0.409199  0.549594  0.027559  0.753513  0.538143
city_2 2010  0.329732  0.788429  0.303195  0.453498  0.134042  0.403113
       2020  0.203455  0.262313  0.750365  0.280409  0.485191  0.980737
3. Выполнить запрос на получение следующих данных 

- все данные по person_1 и person_3
worker       person_1            person_3          
job             job_1     job_2     job_1     job_2
city   year                

In [23]:
# Перегруппировка мультииндексов
index = pd.MultiIndex.from_product(
    [
        ['a', 'c', 'b'],
        [1,2]
    ]
)

data = pd.Series(rng.random(6), index = index)
data.index.names = ['char', 'int']
print(data)

# print(data['a': 'b'])

data = data.sort_index()
print(data)

print(data['a': 'b'])

char  int
a     1      0.961657
      2      0.724790
c     1      0.541227
      2      0.276891
b     1      0.160652
      2      0.969925
dtype: float64
char  int
a     1      0.961657
      2      0.724790
b     1      0.160652
      2      0.969925
c     1      0.541227
      2      0.276891
dtype: float64
char  int
a     1      0.961657
      2      0.724790
b     1      0.160652
      2      0.969925
dtype: float64


In [24]:
index = [
    ('city_1', 2010,1),
    ('city_1', 2010,2),

    ('city_1', 2020,1),
    ('city_1', 2020,2),

    ('city_2', 2010,1),
    ('city_2', 2010,2),

    ('city_2', 2020,1),
    ('city_2', 2020,2),

    ('city_3', 2010,1),
    ('city_3', 2010,2),

    ('city_3', 2020,1),
    ('city_3', 2020,2),
    ]

population  = [
    101,
    1010,
    201,
    2020,
    101,
    1010,
    201,
    2010,
    103,
    1030,
    203,
    2030
]

pop = pd.Series(population, index = index)
print(pop)

i = pd.MultiIndex.from_tuples(index)

pop = pop.reindex(i)
print(pop)
print()
print(pop.unstack(level=0))
print()
print(pop.unstack(level=1))
print()
print(pop.unstack(level=2))

(city_1, 2010, 1)     101
(city_1, 2010, 2)    1010
(city_1, 2020, 1)     201
(city_1, 2020, 2)    2020
(city_2, 2010, 1)     101
(city_2, 2010, 2)    1010
(city_2, 2020, 1)     201
(city_2, 2020, 2)    2010
(city_3, 2010, 1)     103
(city_3, 2010, 2)    1030
(city_3, 2020, 1)     203
(city_3, 2020, 2)    2030
dtype: int64
city_1  2010  1     101
              2    1010
        2020  1     201
              2    2020
city_2  2010  1     101
              2    1010
        2020  1     201
              2    2010
city_3  2010  1     103
              2    1030
        2020  1     203
              2    2030
dtype: int64

        city_1  city_2  city_3
2010 1     101     101     103
     2    1010    1010    1030
2020 1     201     201     203
     2    2020    2010    2030

          2010  2020
city_1 1   101   201
       2  1010  2020
city_2 1   101   201
       2  1010  2010
city_3 1   103   203
       2  1030  2030

               1     2
city_1 2010  101  1010
       2020  201  2020


In [25]:
## NumPy Конкатенация
x = [1,2,3]
y = [4,5,6]
z = [7,8,9]
print(np.concatenate([x,y,z]))

x = [[1,2,3]]
y = [[4,5,6]]
z = [[7,8,9]]
print(np.concatenate([x,y,z], axis=0))
print(np.concatenate([x,y,z], axis=1))


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]


In [26]:
## Pd Конкатенация

ser1 = pd.Series(['a', 'b', 'c'], index = [1,2,3])
ser2 = pd.Series(['d', 'e', 'f'], index = [4,5,6])

print(pd.concat([ser1, ser2]))

1    a
2    b
3    c
4    d
5    e
6    f
dtype: object


In [27]:
ser1 = pd.Series(['a', 'b', 'c'], index = [1,2,3])
ser2 = pd.Series(['d', 'e', 'f'], index = [1,2,6])
print(pd.concat([ser1, ser2], verify_integrity=False))

1    a
2    b
3    c
1    d
2    e
6    f
dtype: object


In [28]:
ser1 = pd.Series(['a', 'b', 'c'], index = [1,2,3])
ser2 = pd.Series(['d', 'e', 'f'], index = [1,2,6])
print(pd.concat([ser1, ser2], ignore_index=True))

0    a
1    b
2    c
3    d
4    e
5    f
dtype: object


In [29]:
ser1 = pd.Series(['a', 'b', 'c'], index = [1,2,3])
ser2 = pd.Series(['d', 'e', 'f'], index = [1,2,6])
print(pd.concat([ser1, ser2], keys = ['x', 'y']))

x  1    a
   2    b
   3    c
y  1    d
   2    e
   6    f
dtype: object


In [50]:
ser1 = pd.Series(['a', 'b', 'c'], index = [1,2,3])
ser2 = pd.Series(['b', 'c', 'f'], index = [4,5,6])

print(pd.concat([ser1, ser2], join = 'outer'))
print(pd.concat([ser1, ser2], join = 'inner'))

1    a
2    b
3    c
4    b
5    c
6    f
dtype: object
1    a
2    b
3    c
4    b
5    c
6    f
dtype: object


In [63]:
#4. Привести пример использования inner и outer джойнов для Series (данные примера скорее всего нужно изменить)
ser1 = pd.Series(['a', 'b', 'c'], index=[1,2,3])
ser2 = pd.Series(['b', 'c', 'f'], index=[2,3,4])

print("Outer join (объединение всех):")
print(pd.concat([ser1, ser2], axis=1, join='outer'))

print("Inner join (только общие):")
print(pd.concat([ser1, ser2], axis=1, join='inner'))


# print (pd.concat([ser1, ser2], join='outer'))
# print (pd.concat([ser1, ser2], join='inner'))

Outer join (объединение всех):
     0    1
1    a  NaN
2    b    b
3    c    c
4  NaN    f
Inner join (только общие):
   0  1
2  b  b
3  c  c
